name: flutter_portfolio
description: portfolio
version: 1.0.0+1

environment:
  sdk: ">=2.11.0-213.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluro: ^2.0.3
  flutter_bloc: ^6.1.0
  bloc: ^6.1.0
  font_awesome_flutter: ^8.5.0
  url_launcher: ^6.0.2
  flutter_markdown: ^0.6.0
  google_fonts: ^1.1.2
  flutter_spinkit: ^5.0.0
  titled_navigation_bar: ^4.1.0
  graphql: ^4.0.1
  gql: ^0.12.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/about.json
    - assets/works.json
    - assets/skills.json
    - assets/contents/
    - assets/posts/
analyzer:
  enable-experiment:
    - non-nullable
