name: flutter_portfolio
description: portfolio
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluro: ^2.0.3
  flutter_bloc: ^7.0.0
  bloc: ^7.0.0
  font_awesome_flutter: ^9.0.0-nullsafety
  url_launcher: ^6.0.2
  flutter_markdown: ^0.6.0
  google_fonts: ^2.0.0
  flutter_spinkit: ^5.0.0
  titled_navigation_bar: ^5.0.0-nullsafety.0
  graphql: ^5.0.0-nullsafety.3
  gql: ^0.13.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/about.json
    - assets/works.json
    - assets/skills.json
    - assets/contents/
    - assets/posts/
analyzer:
  enable-experiment:
    - non-nullable
