name: flutter_portfolio
description: portfolio
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  fluro: ^1.6.2
  flutter_bloc: ^3.2.0
  bloc: ^3.0.0
  font_awesome_flutter: ^8.5.0
  url_launcher: ^5.2.7
  flutter_markdown: ^0.3.2
  google_fonts: ^0.2.0
  badges: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/about.json
    - assets/works.json
    - assets/skills.json
    - assets/blog.json
    - assets/contents/
    - assets/posts/
